// <auto-generated />
namespace CIS174_Final_Mesinovic.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class err_migr2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(err_migr2));
        
        string IMigrationMetadata.Id
        {
            get { return "201902270106532_err_migr2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
